; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Aug 04 2020 18:22:47 GMT+0300 (RTZ 2 (зима))
; ================================================================================

InstaMap:
	dc.w InstaMap_0-InstaMap, InstaMap_1-InstaMap
	dc.w InstaMap_2-InstaMap, InstaMap_3-InstaMap
	dc.w InstaMap_4-InstaMap, InstaMap_5-InstaMap
	dc.w InstaMap_6-InstaMap, InstaMap_7-InstaMap
InstaMap_0: dc.b $3
	dc.b $E8, $8, $0, $0, $F0
	dc.b $F0, $4, $0, $3, $F8
	dc.b $F8, $0, $0, $5, $0
InstaMap_1: dc.b $3
	dc.b $F0, $4, $0, $6, $8
	dc.b $F8, $8, $0, $8, $0
	dc.b $0, $4, $0, $B, $0
InstaMap_2: dc.b $2
	dc.b $0, $9, $0, $D, $0
	dc.b $10, $C, $0, $13, $F8
InstaMap_3: dc.b $3
	dc.b $F0, $C, $0, $0, $E8
	dc.b $F8, $8, $0, $4, $E8
	dc.b $0, $6, $0, $7, $E8
InstaMap_4: dc.b $3
	dc.b $E8, $4, $0, $D, $F0
	dc.b $E8, $B, $0, $F, $0
	dc.b $8, $4, $0, $1B, $8
InstaMap_5: dc.b $3
	dc.b $F0, $4, $18, $1B, $E8
	dc.b $F8, $B, $18, $F, $E8
	dc.b $10, $4, $18, $D, $0
InstaMap_6: dc.b $0
InstaMap_7: dc.b $0
	even